---

- name: install java java-1.8.0-openjdk.x86_64
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present
  

- name: manage java.sh in profile.d
  template:
    src: java.sh.j2
    dest: /etc/profile.d/java.sh
  

 
