---

- name: Download Maven
  get_url: url=https://mirrors.ukfast.co.uk/sites/ftp.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz dest=/opt/

- name: unarchive maven
  unarchive:
    src: /opt/apache-maven-3.6.3-bin.tar.gz
    dest: /opt/
    remote_src: yes

- name: link maven
  file: 
    src: "/opt/apache-maven-3.6.3"
    dest: /opt/maven
    state: link

- name: config mavan in profile.d
  template:
    src: maven.sh.j2
    dest: /etc/profile.d/maven.sh

