---

- name: Install Jenkins and its Java dependencies over HTTP with tomcat  in RedHat base systems 
  hosts: server01
  become: yes
  become_user: root
  roles:
    - java
    - tomcat
    - jenkins
    - maven

  
